name: Build .NET Core

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: nelonoel/branch-name@v1
            -   uses: actions/setup-dotnet@v1.5.0
                with:
                    dotnet-version: 3.1.301
            
            -   name: Install dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --configuration Release --no-restore
            -   name: Test
                run: dotnet test --no-restore --verbosity normal
            -   name: Pack
                run: dotnet pack --no-build --configuration Release --output .
            -   name: PushGithub
                run: dotnet nuget push cs-ijson-microservice.nupkg --no-symbols --skip-duplicate
                env:
                    NUGET_AUTH_TOKEN: ${{ github.token }}