name: Build .NET Core

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: nelonoel/branch-name@v1
            -   uses: actions/setup-dotnet@v1.5.0
                with:
                    dotnet-version: 3.1.301
                    source-url: https://nuget.pkg.github.com/kakadu-dev/index.json
                env:
                    NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            -   name: Install dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --configuration Release --no-restore
            -   name: Test
                run: dotnet test --no-restore --verbosity normal
            -   name: Pack
                run: dotnet pack --no-build --configuration Release --output .
            -   name: PushGithub
                run: dotnet nuget push *.nupkg --skip-duplicate --no-symbols true
